name: TF Auto Formatting

description: Automates tf formatting, docs and validation

inputs:
  mode:
    description: Mode to run in. Valid Options are validate, check-fmt, check-docs, auto-fmt, auto-docs or auto-update.
    required: true
    default: validate
  working-dir:
    description: working dir to run checks from
    required: false
    default: ""
  github_token:
    description: 'GitHub token or PAT token'
    required: false
    default: ${{ github.token }}
  github_url:
    description: 'GitHub url or GitHub Enterprise url'
    required: false
    default: ${{ github.server_url }}
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ${{ github.repository }}
    required: false
      
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
  - name: Validate
    if: ${{ inputs.mode == 'validate' }} 
    working-directory: ${{ github.action_path }}
    run: ${{ github.action_path }}/tf_check.sh validate
    env:
      SHA: ${{ github.sha }}
    shell: bash
  - name: Auto Update Docs and Formatting
    if: ${{ inputs.mode == 'auto-update' }} 
    working-directory: ${{ github.action_path }}
    run: ${{ github.action_path }}/tf_check.sh auto-update
    env:
      SHA: ${{ github.sha }}
    shell: bash